version: '3.8'

services:
  # Server service
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped

  # Client service
  # client:
  #   build:
  #     context: .
  #     dockerfile: client/Dockerfile
  #   ports:
  #     - "3001:3001"
  #   restart: unless-stopped
